/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddAdmin: typeof import('./src/views/admins/addAdmin.vue')['default']
    AddBuch: typeof import('./src/views/buchs/addBuch.vue')['default']
    AddBuchAttach: typeof import('./src/views/buchs/attach/addBuchAttach.vue')['default']
    AddPublisher: typeof import('./src/views/publishers/addPublisher.vue')['default']
    AddUser: typeof import('./src/views/users/addUser.vue')['default']
    BaseAdmin: typeof import('./src/views/admins/baseAdmin.vue')['default']
    BaseBuch: typeof import('./src/views/buchs/baseBuch.vue')['default']
    BaseCommList: typeof import('./src/views/buchs/comments/baseCommList.vue')['default']
    BaseOrder: typeof import('./src/views/orders/baseOrder.vue')['default']
    BasePublisher: typeof import('./src/views/publishers/basePublisher.vue')['default']
    BaseUser: typeof import('./src/views/users/baseUser.vue')['default']
    DeleteBuchAttach: typeof import('./src/views/buchs/attach/deleteBuchAttach.vue')['default']
    DetailPublisher: typeof import('./src/views/publishers/detailPublisher.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpBox: typeof import('~icons/ep/box')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpManagement: typeof import('~icons/ep/management')['default']
    IEpNotebook: typeof import('~icons/ep/notebook')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IndexAdmin: typeof import('./src/views/admins/indexAdmin.vue')['default']
    IndexBuch: typeof import('./src/views/buchs/indexBuch.vue')['default']
    IndexOrder: typeof import('./src/views/orders/indexOrder.vue')['default']
    IndexPublisher: typeof import('./src/views/publishers/indexPublisher.vue')['default']
    IndexUser: typeof import('./src/views/users/indexUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./src/views/signin.vue')['default']
    Signup: typeof import('./src/views/signup.vue')['default']
    TopCustNavigation: typeof import('./src/segements/top-cust-navigation.vue')['default']
    UpdateBuch: typeof import('./src/views/buchs/updateBuch.vue')['default']
    Views: typeof import('./src/views/index.vue')['default']
  }
}
