/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carts: typeof import('./src/views/Carts.vue')['default']
    Category: typeof import('./src/views/Category.vue')['default']
    CategoryBar: typeof import('./src/components/CategoryBar.vue')['default']
    Collection: typeof import('./src/views/Collection.vue')['default']
    Detail: typeof import('./src/views/Detail.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpBottom: typeof import('~icons/ep/bottom')['default']
    IEpCoin: typeof import('~icons/ep/coin')['default']
    IEpIphone: typeof import('~icons/ep/iphone')['default']
    IEpKey: typeof import('~icons/ep/key')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpTimer: typeof import('~icons/ep/timer')['default']
    IEpTop: typeof import('~icons/ep/top')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpVan: typeof import('~icons/ep/van')['default']
    IEpWallet: typeof import('~icons/ep/wallet')['default']
    Index: typeof import('./src/views/Index.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Orders: typeof import('./src/views/Orders.vue')['default']
    OrdersData: typeof import('./src/segments/OrdersData.vue')['default']
    PaySuccess: typeof import('./src/segments/PaySuccess.vue')['default']
    Publishers: typeof import('./src/views/Publishers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/views/Search.vue')['default']
    SignIn: typeof import('./src/views/SignIn.vue')['default']
    SignUp: typeof import('./src/views/SignUp.vue')['default']
    Space: typeof import('./src/views/Space.vue')['default']
  }
}
