/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carts: typeof import('./src/views/carts.vue')['default']
    Category: typeof import('./src/views/category.vue')['default']
    CategoryBar: typeof import('./src/components/category-bar.vue')['default']
    Collection: typeof import('./src/views/collection.vue')['default']
    Detail: typeof import('./src/views/detail.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpBottom: typeof import('~icons/ep/bottom')['default']
    IEpCoin: typeof import('~icons/ep/coin')['default']
    IEpIphone: typeof import('~icons/ep/iphone')['default']
    IEpKey: typeof import('~icons/ep/key')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpTimer: typeof import('~icons/ep/timer')['default']
    IEpTop: typeof import('~icons/ep/top')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpVan: typeof import('~icons/ep/van')['default']
    IEpWallet: typeof import('~icons/ep/wallet')['default']
    Navigation: typeof import('./src/components/navigation.vue')['default']
    Orders: typeof import('./src/views/orders.vue')['default']
    OrdersData: typeof import('./src/segments/orders-data.vue')['default']
    PaySuccess: typeof import('./src/segments/pay-success.vue')['default']
    Publishers: typeof import('./src/views/publishers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/views/search.vue')['default']
    Signin: typeof import('./src/views/signin.vue')['default']
    Signup: typeof import('./src/views/signup.vue')['default']
    Space: typeof import('./src/views/space.vue')['default']
    Views: typeof import('./src/views/index.vue')['default']
  }
}
